version: '3'

# als = asanda learning service
services:
  als-primary-postgres-database:
    image: postgres:16
    restart: no #setting to no because this is for learning and i don't want it to start up unless i intentionally start it up. 
    shm_size: 128mb
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    ports:
      - "5432:5432"
    volumes:
      -  C:\learning\postgressql\volumes\alv-primary-postgres-database:/var/lib/postgresql/data
    networks:
      aln-databases:
        aliases:
          - alsa-primary-postgres-database

  pdadmin:
    image: dpage/pgadmin4:8.14.0
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:?default_email_required}
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 8081:80
    volumes:
      - C:\learning\postgressql\volumes\alv-pdadmin:/var/lib/pgadmin
      - C:\learning\postgressql\volumes\alv-pdadmin-storage-import:/var/lib/pgadmin/storage/${PGADMIN_DEFAULT_EMAIL:?default_email_required}
    networks:
      aln-databases:
        aliases:
          - alsa-pgadmin

networks:
  aln-databases:
    driver: bridge
